/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicatiesRouteImport } from './routes/publicaties'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as OpdrachtgeversRouteImport } from './routes/opdrachtgevers'
import { Route as KetenmetingenRouteImport } from './routes/ketenmetingen'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicatiesIndexRouteImport } from './routes/publicaties.index'
import { Route as PublicatiesSlugRouteImport } from './routes/publicaties.$slug'

const PublicatiesRoute = PublicatiesRouteImport.update({
  id: '/publicaties',
  path: '/publicaties',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const OpdrachtgeversRoute = OpdrachtgeversRouteImport.update({
  id: '/opdrachtgevers',
  path: '/opdrachtgevers',
  getParentRoute: () => rootRouteImport,
} as any)
const KetenmetingenRoute = KetenmetingenRouteImport.update({
  id: '/ketenmetingen',
  path: '/ketenmetingen',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicatiesIndexRoute = PublicatiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicatiesRoute,
} as any)
const PublicatiesSlugRoute = PublicatiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicatiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ketenmetingen': typeof KetenmetingenRoute
  '/opdrachtgevers': typeof OpdrachtgeversRoute
  '/over-ons': typeof OverOnsRoute
  '/publicaties': typeof PublicatiesRouteWithChildren
  '/publicaties/$slug': typeof PublicatiesSlugRoute
  '/publicaties/': typeof PublicatiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ketenmetingen': typeof KetenmetingenRoute
  '/opdrachtgevers': typeof OpdrachtgeversRoute
  '/over-ons': typeof OverOnsRoute
  '/publicaties/$slug': typeof PublicatiesSlugRoute
  '/publicaties': typeof PublicatiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/ketenmetingen': typeof KetenmetingenRoute
  '/opdrachtgevers': typeof OpdrachtgeversRoute
  '/over-ons': typeof OverOnsRoute
  '/publicaties': typeof PublicatiesRouteWithChildren
  '/publicaties/$slug': typeof PublicatiesSlugRoute
  '/publicaties/': typeof PublicatiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/ketenmetingen'
    | '/opdrachtgevers'
    | '/over-ons'
    | '/publicaties'
    | '/publicaties/$slug'
    | '/publicaties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/ketenmetingen'
    | '/opdrachtgevers'
    | '/over-ons'
    | '/publicaties/$slug'
    | '/publicaties'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/ketenmetingen'
    | '/opdrachtgevers'
    | '/over-ons'
    | '/publicaties'
    | '/publicaties/$slug'
    | '/publicaties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  KetenmetingenRoute: typeof KetenmetingenRoute
  OpdrachtgeversRoute: typeof OpdrachtgeversRoute
  OverOnsRoute: typeof OverOnsRoute
  PublicatiesRoute: typeof PublicatiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publicaties': {
      id: '/publicaties'
      path: '/publicaties'
      fullPath: '/publicaties'
      preLoaderRoute: typeof PublicatiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opdrachtgevers': {
      id: '/opdrachtgevers'
      path: '/opdrachtgevers'
      fullPath: '/opdrachtgevers'
      preLoaderRoute: typeof OpdrachtgeversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketenmetingen': {
      id: '/ketenmetingen'
      path: '/ketenmetingen'
      fullPath: '/ketenmetingen'
      preLoaderRoute: typeof KetenmetingenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaties/': {
      id: '/publicaties/'
      path: '/'
      fullPath: '/publicaties/'
      preLoaderRoute: typeof PublicatiesIndexRouteImport
      parentRoute: typeof PublicatiesRoute
    }
    '/publicaties/$slug': {
      id: '/publicaties/$slug'
      path: '/$slug'
      fullPath: '/publicaties/$slug'
      preLoaderRoute: typeof PublicatiesSlugRouteImport
      parentRoute: typeof PublicatiesRoute
    }
  }
}

interface PublicatiesRouteChildren {
  PublicatiesSlugRoute: typeof PublicatiesSlugRoute
  PublicatiesIndexRoute: typeof PublicatiesIndexRoute
}

const PublicatiesRouteChildren: PublicatiesRouteChildren = {
  PublicatiesSlugRoute: PublicatiesSlugRoute,
  PublicatiesIndexRoute: PublicatiesIndexRoute,
}

const PublicatiesRouteWithChildren = PublicatiesRoute._addFileChildren(
  PublicatiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  KetenmetingenRoute: KetenmetingenRoute,
  OpdrachtgeversRoute: OpdrachtgeversRoute,
  OverOnsRoute: OverOnsRoute,
  PublicatiesRoute: PublicatiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
